In [1]:
import torch

In [13]:
A = torch.arange(40).reshape(2,5,4)
A,A.shape,A.sum()

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]),
 torch.Size([2, 5, 4]),
 tensor(780))

In [14]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0

tensor([[20, 22, 24, 26],
        [28, 30, 32, 34],
        [36, 38, 40, 42],
        [44, 46, 48, 50],
        [52, 54, 56, 58]])

对哪个维度求和，就相当于把哪个维度压缩

In [15]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1

tensor([[ 40,  45,  50,  55],
        [140, 145, 150, 155]])

In [53]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

预留空间存储梯度

In [54]:
x.requires_grad_(True)    #等价于 x = torch.arange(4.0, requires_grad=True)
#x.grad
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [55]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [56]:
x.grad == 4*x

tensor([True, True, True, True])

In [58]:
x.grad.zero_()    pytorch存在梯度累加机制(从实际使用上来说，是一种减小内存负单的trick，可以累加上一次batch计算出的的梯度。本试验不需此操作，故需要先把梯度归0)
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

可以将某些计算移动到记录的计算图之外

In [62]:
x.grad.zero_()
y = x * x
u = y.detach()    #此指：把y当前计算得到的值当做一个常数而非函数赋值给u。在一些网络需要将部分参数进行固定时可以用到该trick
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [63]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [81]:
w = torch.tensor([2,-3.4])
len(w)

2

In [80]:
x = torch.normal(0,1,(5,len(w)))    #生成一系列均值为0，方差为1的随机数(这些数构成一个形状为5行，len(w)列的矩阵)
x
x.shape

torch.Size([5, 2])

In [82]:
t = torch.matmul(x,w)
t.shape

torch.Size([5])