In [1]:
import torch
import math
import time
import numpy as np
from d2l import torch as d2l

In [2]:
n = 1000
a = torch.ones(n)
b = torch.ones(n)

In [3]:
class Timer:
    def __init__(self):
        self.times = []
        self.start()

        
    def start(self):
        self.tik = time.time()
        
    def stop(self):
        self.times.append(time.time() - self.tik)
        return self.times[-1]
    
    def avg(self):
        return sum(self.times) / len(self.times)
    
    def sum(self):
        return sum(self.times)
    
    def cumsum(self):
        return np.array(self.times).cumsum().tolist()

In [6]:
c = torch.zeros(n)
timer = Timer()

for i in range(n):
    c[i] = a[i] + b[i]
f'{timer.stop():.5f} sec'

'0.03000 sec'

In [7]:
timer.start()
d = a + b
f'{timer.stop():.5f} sec'

'0.00000 sec'

In [9]:
x = torch.randn(3, requires_grad=True)


y = x * 2
while y.data.norm() < 1000:
    y = y * 2
    
print(x)    
print(y)

tensor([-0.4476,  0.2976, -0.1235], requires_grad=True)
tensor([-916.6630,  609.4670, -252.9214], grad_fn=<MulBackward0>)


In [10]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(v)

print(v)
print(x.grad)

tensor([1.0000e-01, 1.0000e+00, 1.0000e-04])
tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [16]:
xx = torch.randn(1,1,32,32)

def num_flat_features(x):
    size = x.size()[1:]
    n = 1
    for s in size:
        n *= s
    return n

nnn = num_flat_features(x=xx)
print(nnn)

1024
