In [1]:
# import cv2
import numpy as np
import tensorflow as tf

In [2]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[7,8]])
s = tf.matmul(a,b)
s

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [10]:
random_float = tf.random.uniform(shape=())
zero_vector = tf.zeros(shape=(2))
print(random_float,zero_vector)

tf.Tensor(0.43547034, shape=(), dtype=float32) tf.Tensor([0. 0.], shape=(2,), dtype=float32)


In [13]:
x = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
    y = tf.square(x)
y_grad = tape.gradient(y,x)
print([y,y_grad])

[<tf.Tensor: shape=(), dtype=float32, numpy=9.0>, <tf.Tensor: shape=(), dtype=float32, numpy=6.0>]
